"""messages

Revision ID: d88792a888a4
Revises: ca5c386dde13
Create Date: 2025-12-10 22:13:39.984949

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d88792a888a4"
down_revision: Union[str, Sequence[str], None] = "ca5c386dde13"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messaging_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("request_file_id", sa.Integer(), nullable=False),
        sa.Column("attachment_file_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("sending_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("generated", sa.Boolean(), nullable=False),
        sa.Column("default_text", sa.Text(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["attachment_file_id"], ["files.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["request_file_id"], ["files.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_messaging_requests_attachment_file_id"),
        "messaging_requests",
        ["attachment_file_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_messaging_requests_id"), "messaging_requests", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_messaging_requests_request_file_id"),
        "messaging_requests",
        ["request_file_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_messaging_requests_session_id"),
        "messaging_requests",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_messaging_requests_user_id"),
        "messaging_requests",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message_request_id", sa.Integer(), nullable=False),
        sa.Column(
            "sending_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sent_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("phone_number", sa.String(length=50), nullable=True),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("user_id", sa.String(length=255), nullable=True),
        sa.Column("attachment_file_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "failed", "successful", name="message_status"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["attachment_file_id"], ["files.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["message_request_id"], ["messaging_requests.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_messages_attachment_file_id"),
        "messages",
        ["attachment_file_id"],
        unique=False,
    )
    op.create_index(op.f("ix_messages_id"), "messages", ["id"], unique=False)
    op.create_index(
        op.f("ix_messages_message_request_id"),
        "messages",
        ["message_request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_messages_phone_number"), "messages", ["phone_number"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_phone_number"), table_name="messages")
    op.drop_index(op.f("ix_messages_message_request_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_attachment_file_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(
        op.f("ix_messaging_requests_user_id"), table_name="messaging_requests"
    )
    op.drop_index(
        op.f("ix_messaging_requests_session_id"), table_name="messaging_requests"
    )
    op.drop_index(
        op.f("ix_messaging_requests_request_file_id"), table_name="messaging_requests"
    )
    op.drop_index(op.f("ix_messaging_requests_id"), table_name="messaging_requests")
    op.drop_index(
        op.f("ix_messaging_requests_attachment_file_id"),
        table_name="messaging_requests",
    )
    op.drop_table("messaging_requests")
    # ### end Alembic commands ###
